### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ceee**
This commits upgrades the Nancy dependencies to the current 0.23 version, which also removed the `Fragment` property from `Nancy.Url`.

### CODE REVIEW

**Comment by jgillich** [comment]
Does your fork work with Nancy 0.23? The last time I tried LightningCache, it didn't work (using Nancy 0.21 IIRC). Since @creamdog doesn't seem to maintain this project anymore, it would be awesome if he would let someone else take over.

**Comment by ceee** [comment]
@jgillich Yes, it works. That's what this PR is for. I am using it in project without any problems atm.
So, just use my [fork](https://github.com/ceee/Nancy.LightningCache) to get a copy which works with Nancy 0.23

**Comment by jgillich** [comment]
That's great to hear, thanks for your work, I will try it out soon! I still find it a bit unfortunate that the only caching extension for Nancy on NuGet does not work with newer versions. Did you ever consider making your fork "official" and uploading it on NuGet? @creamdog hasn't been particularly active for a long time.

**Comment by ceee** [comment]
@jgillich I have created my own [repo](https://github.com/ceee/Nancy.LightningCache) and uploaded it to [NuGet](https://www.nuget.org/packages/Nancy.LightningCache.2/).

**Pull request closed without merging**
